blank_issues_enabled: true
contact_links:
- name: ğŸ™‹ğŸ¤”â€Question/Doubt
  url: https://app.stackup.dev
  about: Feel free to ask any questions on our Slack channel.
- name: DOK Community support
   url: https://discord.com/invite/wVtcAT9kqU
   about: Feel free to get involved and clear your doubts here.